### ISSUE TITLE
Where test suite should be located at?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/distributed-tracing-wg#2]
@plehegar I see a copy of [tracecontext test suite](https://github.com/w3c/trace-context/tree/master/test) in this repo. Is this repo the right place for that test suite? 

I like when test suite is part of specs repo. This way a single PR can suggest the change in wording as well as a fix for tests. But if it's not aligned to how W3C operates - it's fine. Definitely should avoid having two copies

**Comment by plehegar** [comment]
Ideally, we would thrive to be part of WPT. This may not happen anytime soon given that we need a dedicated infrastructure. I left the copy in this repo just in case but I believe we can remove it.
