### ISSUE TITLE
Expected Completion dates

### ISSUE THREAD

**Issue by plehegar** [w3c/distributed-tracing-wg#27]
Should we have expected completion dates for any of our specification listed in our draft charter:
 https://htmlpreview.github.io/?https://github.com/w3c/distributed-tracing-wg/blob/master/charter/2020.html

Unless I hear otherwise, I'll propose to remove them.

@mtwo @SergeyKanzhelev @danielkhan

**Comment by SergeyKanzhelev** [comment]
When we are saying "Expected completion: Q2 2021" - we are talking about final recommendation, correct? Can you please remind on how much time is in between different levels of maturity?
