### ISSUE TITLE
charter: fix or remove broken links to docs

### ISSUE THREAD

**Issue by samuelweiler** [w3c/distributed-tracing-wg#34]
Three links to deliverables (the last three) are broken.

**Comment by plehegar** [comment]
Those were fixed in
 https://github.com/w3c/distributed-tracing-wg/commit/07cd9829a47dcd74c18c73aef5b0ebd56c232bf1#diff-a30c76614a9eb9dc94198ea45e502e53
but the draft wasn't mirrored on the W3C website. Now fixed in
https://www.w3.org/2020/03/proposed-distributed-tracing-wg.html

**Comment by plehegar** [comment]
(closing as resolved. feel free to reopen if you believe otherwise)
