### ISSUE TITLE
charter: clarify if/how/when this touches browsers and users

### ISSUE THREAD

**Issue by samuelweiler** [w3c/distributed-tracing-wg#35]
I want to charter to be more clear about if and when this technology will touch browsers.  I understand that there is an intention, in the new work proposed, to bring things back to the browser - and I want the charter to be explicit about that, one way or the other.

**Comment by samuelweiler** [comment]
also see https://github.com/w3c/trace-context/issues/392

**Comment by plehegar** [comment]
Proposed text is:
[[
This update is intended to include a mechanism to carry context information in protocol responses, thus allowing context information to be accessed in Web browsers.
]]

**Comment by samuelweiler** [comment]
That's not really clear to me - what's the wordier version?

**Comment by plehegar** [comment]
I included some wording. Hopefully this is good enough for now.
