### ISSUE TITLE
charter: plan for getting user consent

### ISSUE THREAD

**Issue by samuelweiler** [w3c/distributed-tracing-wg#36]
On the assumption that the new specs being developed are intended to touch the browser (see https://github.com/w3c/distributed-tracing-wg/issues/35)...

This technology looks at best like third-party cookies come back from the grave and at worst like more invasive active spyware.  While generally unacceptable, that might be tolerable in some limited contexts, like having it deliberately and explicitly turned on for limited time intervals for debugging purposes.  To that end, how does the WG intend to request informed consent from the user?  Do you need protocol elements to ask for it in real time?  If so, please add appropriate work items to the charter.  Contemplate how to ask for consent for different time intervals (e.g. 90 seconds for automated debugging, 15 minutes for human-involved debugging, or 24 hours for intermittent issues, how to deal with language issues, and how to scope the consent to the least-invasive possible form (e.g. listing specific domains or even hosts).  (Yes, these are hard problems.)

**Comment by plehegar** [comment]
[[
The Group will address privacy considerations related to fingerprinting and exposing identifiers, in particular whether user consent should be required. 
]]

**Comment by samuelweiler** [comment]
I still want direct answers to the questions asked above:

> how does the WG intend to request informed consent from the user? Do you need protocol elements to ask for it in real time? 

I'm think it's okay to limit the mitigations scope text to the one deliverable, but I want the charter to be more specific.  I suggest:

> The revision must define mechanisms that mitigate both fingerprinting and other privacy risks exposed by Trace Context. If the mitigations include explicit or implicit user consent, as anticipated, the WG will define any necessary protocol elements for seeking that consent and formulate mechanisms for constraining the requests and resultant consent to the least-invasive possible form (e.g. listing specific domains or even hosts, as well as temporally limiting the permission consistent with the use case).

**Comment by plehegar** [comment]
I don't think you can get a direct answer in the charter and the Group hasn't figured that out yet.

Your proposed text sounds good to me.

@danielkhan @mtwo , wdyt?

**Comment by samuelweiler** [comment]
> I don't think you can get a direct answer in the charter and the Group hasn't figured that out yet.

I'm not asking for the answer in the charter.  I'm asking for the answer here, in this thread, to inform the charter.  "We don't know" is direct enough, if worrisome.

**Comment by yurishkuro** [comment]
> fingerprinting and other privacy risks exposed by Trace Context

Many of us are not security experts. Can you elaborate why you think these risks even exist in and/or influenced by the Trace Context protocol?

**Comment by samuelweiler** [comment]
> Many of us are not security experts. Can you elaborate why you think these risks even exist in and/or influenced by the Trace Context protocol?

Not in this format.  If the chairs want to arrange a discussion, they are welcome to reach out.

In any case, the merged PR resolves this issue to my satisfaction.  Closing this issue.
