### ISSUE TITLE
charter: mark internal review snapshot as obsolete.

### ISSUE THREAD

**Issue by samuelweiler** [w3c/distributed-tracing-wg#39]
The [snapshot circulated for internal review](https://www.w3.org/2020/03/proposed-distributed-tracing-wg.html) needs a marker that it is out of date.

A [new shapshot](https://www.w3.org/2020/05/proposed-dt-wg-charter.html) has gone out for member review.

**Comment by samuelweiler** [comment]
Presumptively the AC review snapshot should not also be marked as obsolete, with a pointer to the approved charter (if any).

**Comment by caribouW3** [comment]
Both proposals marked as obsolete, with link to final (approved) charter.

**Comment by samuelweiler** [comment]
Thank you!
