### ISSUE TITLE
Change Bi-Weekly meeting time

### ISSUE THREAD

**Issue by danielkhan** [w3c/distributed-tracing-wg#41]
To accommodate time conflicts for key members, I'd like to propose to change the meeting time to

12:00pm PT
03:00pm ET
09:00pm CET

Please add your vote - if this creates new conflicts, I will set up a Doodle to offer more options.

**Comment by mtwo** [comment]
@SergeyKanzhelev does the new time work for you? :)

**Comment by SergeyKanzhelev** [comment]
@mtwo yes, thank you!

**Comment by MrAlias** [comment]
The day doesn't change, this is still recurring on Tuesdays, right?

**Comment by subvocal** [comment]
That time works for me.

**Comment by danielkhan** [comment]
> The day doesn't change, this is still recurring on Tuesdays, right?

Correct. Same day, same cadence, different time.

**Comment by danielkhan** [comment]
This was broadly agreed on. I changed the date.
