### ISSUE TITLE
Rename the correlation-context repo to baggage

### ISSUE THREAD

**Issue by danielkhan** [w3c/distributed-tracing-wg#42]
As discussed on https://github.com/w3c/correlation-context/issues/17
Please rename the repo `correlation-context` to `baggage`.
This requires administrator permissions. @plehegar can you please take care of this. 
The rewording of the spec will take place after this.

**Comment by plehegar** [comment]
https://github.com/w3c/bagagge

**Comment by danielkhan** [comment]
My bad - `baggage` not `bagagge`

**Comment by plehegar** [comment]
https://github.com/w3c/baggage
