### ISSUE TITLE
Virtual workshop in Fall 2020

### ISSUE THREAD

**Issue by danielkhan** [w3c/distributed-tracing-wg#44]
Let's agree on dates and times for the virtual workshop this fall. 
We have a lot of ground to cover. Most importantly
- continuing with the Baggage spec
- revising the Trace Context spec and adding response headers

I am proposing 3-hour slots on **Tuesday**, **Wednesday**, and **Thursday**.
Time: **12pm - 3pm PDT / 3pm - 6pm EDT / 9pm - 12pm CET**.

**Proposed days:**
1. October 13th through 15th
2. October 20th through 22th
3. October 27th through 29th

Please use the comments to register your choice or discuss other options.

**Comment by dyladan** [comment]
Any of those slots is fine with me

**Comment by SergeyKanzhelev** [comment]
these two work better for me:

- October 20th through 22th
- October 27th through 29th

I can make 13th work

**Comment by mwear** [comment]
I can do:

* October 13th through 15th
* October 27th through 29th

**Comment by cwensel** [comment]
All dates are fine with me.

**Comment by justinfoote** [comment]
Any of these dates work for me. 
And I'll circulate this with the other New Relic folks.

**Comment by Kanwaldeep** [comment]
these two work better for me:

October 20th through 22th
October 27th through 29th

I could make 13th work as well.

And I'll circulate with other folks in Msft.

**Comment by caribouW3** [comment]
26th-30th is the TPAC breakouts week, so it may be busy.

**Comment by mwear** [comment]
I'm curious if any decisions have been on the dates. If not, perhaps we can chat about them at the bi-weekly tomorrow.

**Comment by aw100** [comment]
These all work for me.

**Comment by danielkhan** [comment]
Date will be: October 27th through 29th - invite follows.

**Comment by danielkhan** [comment]
Agenda and minutes doc https://docs.google.com/document/d/18sSEBnUaTj_6Z-i9bxqqi_-HOSu_5lmwd-hQbXSYcog/edit?usp=sharing
